"""empty message

Revision ID: 124aa85735fd
Revises: 0217268a3b4a
Create Date: 2019-04-29 11:17:47.576994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124aa85735fd'
down_revision = '0217268a3b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    # ### end Alembic commands ###
